language: java
compiler:
   - jdk
jdk:
  - oraclejdk8
 
install:
   - mkdir -p src/main/java
   - mkdir -p src/main/resources
   - mkdir -p src/test/java
    - mkdir -p src/test/resources
    - mkdir -p target
   - cp -r com src/main/java

script:
  - mvn test -B
  - make -f "Travis.mak" all
 
 
after_success:
  - mvn clean test jacoco:report coveralls:report
# script-orig:
#  - make -f "Travis.mak" all
#  - java oj.test